### ISSUE TITLE
File "<frozen _collections_abc>", line 1063, in index ValueError Error running filter pandoc-tex-numbering.py: Filter returned error status 1

### ISSUE THREAD

**Issue by JPZ4-5** [fncokg/pandoc-tex-numbering#3]
So glad to find this nice project!

When running command below with provided test.tex, it works perfectly well:
```shell
pandoc -o output.docx --filter pandoc-tex-numbering.py test.tex
```
However, when I tried to convert my main.tex into .docx, this traceback occured:
```shell
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\test\pandoc-tex-numbering.py", line 345, in <module>
    main()
  File "C:\Users\admin\Desktop\test\pandoc-tex-numbering.py", line 342, in main
    return run_filters([action_find_labels ,action_replace_refs], doc=doc,prepare=prepare, finalize=finalize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniforge-pypy3\envs\pandoc-py312\Lib\site-packages\panflute\io.py", line 211, in run_filters
    finalize(doc)
  File "C:\Users\admin\Desktop\test\pandoc-tex-numbering.py", line 105, in finalize
    idx = parent.content.index(para)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 1063, in index
ValueError
Error running filter pandoc-tex-numbering.py:
Filter returned error status 1
```

What may cause it and how to fix it?

In pandoc-tex-numbering.log, there are quite a lot WARNING like:
```shell
WARNING Unknown reference-type: eqref
WARNING Unknown reference-type: eqref
WARNING Reference not found: picc
WARNING Reference not found: sec:ISCJ
```

Here is a part of main.tex. If more information might help, I'm willing to provide. Any help will be appreciated!
```latex
\section{间歇采样直接转发干扰}
\label{sec:ISDJ}
间歇采样直接转发干扰(Interrupted-Sampling Directly Jamming, ISDJ)的原理是利用矩形采样脉冲单实现对截获雷达回波信号的部分低速采样。其过程为：干扰机截获雷达信号，立即对雷达信号进行部分采样，将部分采样信号立即转发，下个样周期再对雷达信号进行部分采样并转发，该过程如图\ref{fig:间歇采样直接转发干扰原理图}所示：
\begin{figure}[htbp]
    \centering
    \centerline{\includegraphics[width=0.8\linewidth]{pic/间歇采样直接转发干扰原理图.png}}    
    \caption{间歇采样直接转发干扰原理图}
    \label{fig:间歇采样直接转发干扰原理图}
\end{figure}

图\ref{fig:间歇采样直接转发干扰原理图}中，脉冲宽度为\(T\)，间歇采样信号\(p(t)\)为矩形包络脉冲串，脉宽为\(\tau\)，周期为\(T_s\)，一般的\(T_s < T\)。\(p(t)\)的表达式为式\eqref{eq:ISDJ}：
\begin{align}
p(t) = \text{rect}\left(\frac{t}{\tau}\right) * \sum_{n=-\infty}^{+\infty} \delta(t - n T_s)
\label{eq:ISDJ}
\end{align}
```

Python: 3.12
Windows10

**Comment by fncokg** [comment]
Warnings `"Unknown reference-type: eqref"` and `"Reference not found: xxx"` can be reproduced with your example. This is because the `eqref` command is not supported. I added support for it in commit 44e9095. Now, the warnings are gone.

However, I cannot reproduce the `ValueError` you got. The direct reason of the error is that the filter cannot find a place to add an identifier (in docx, a bookmark) for an equation (`pandoc` does not allow Math objects and Paragraph objects to have an identifier), but I have no idea what the true reason is. I added a `try-except` block to catch the error and print the error information in the log file. Please try the latest version of the filter and provide the log file. Worthmentioning, since I added the `try-except` block, the filter will not crash anymore, and may seem to work as expected, but some link jumps may not work as expected.

**Comment by JPZ4-5** [comment]
Thanks! The log is as below:
```shell
2024-12-25 22:54:02,500 WARNING Reference not found: picb
2024-12-25 22:54:02,500 WARNING Reference not found: picc
2024-12-25 22:54:02,502 WARNING Reference not found: subsec:单通道卷积
2024-12-25 22:54:02,502 WARNING Reference not found: subsec:单通道卷积
2024-12-25 22:54:02,502 WARNING Reference not found: subsubsec:ReLU
2024-12-25 22:54:02,502 WARNING Reference not found: subsubsec:局部连接
2024-12-25 22:54:02,504 WARNING Reference not found: eq:CI--1
2024-12-25 22:54:02,504 WARNING Reference not found: sec:ISDJ
2024-12-25 22:54:02,504 WARNING Reference not found: sec:ISCJ
2024-12-25 22:54:02,504 WARNING Reference not found: sec:SMSP
2024-12-25 22:54:02,504 WARNING Reference not found: sec:CI
2024-12-25 22:54:02,505 WARNING Reference not found: sec:ISDJ
2024-12-25 22:54:02,505 WARNING Reference not found: sec:ISCJ
2024-12-25 22:54:02,505 WARNING Reference not found: sec:NC
2024-12-25 22:54:02,506 WARNING Reference not found: picd
2024-12-25 22:54:02,506 WARNING Reference not found: pice
2024-12-25 22:54:02,507 WARNING Paragraph Para(Math(z_i = \sum_{j=1}^m w_{ij} x_j
    \label{eq:权值计算}\qquad{(3.1)}; format='DisplayMath') SoftBreak Math(a_i = \sigma(z_i + b)
    \label{eq:激活函数}\qquad{(3.2)}; format='DisplayMath')) has been processed before. The labels ['eq:激活函数'] conflict with ['eq:权值计算'].
```

The code arround this WARNING is as below:
```latex
\subsection{神经元}
一个基本的神经元包括 \(3\) 个基本组成部分：输入信号、线性组合和非线性激活函数。式\eqref{eq:权值计算}和式\eqref{eq:激活函数}用于来描述图\ref{fig:神经元示意图}中的神经元的计算。
\begin{figure}[htbp]
    \centering
    \centerline{\includegraphics[width=0.9\linewidth]{pic/神经元示意图.png}}  
    \caption{神经元示意图}
    \label{fig:神经元示意图}
\end{figure}
\begin{equation}
    z_i = \sum_{j=1}^m w_{ij} x_j
    \label{eq:权值计算}
\end{equation}
\begin{equation}
    a_i = \sigma(z_i + b)
    \label{eq:激活函数}
\end{equation}

其中 \(x_0, x_1, \cdots, x_n\) 是输入信号， \(w_{i_0}, w_{i_1}, \cdots, w_{i_m}\) 是神经元的权值， \(z_i\) 是输入信号的线性组合， \(b\) 是偏置，激活函数为 \(\sigma(\cdot)\)， \(a_i\) 是神经元输出信号。

\subsection{激活函数}
激活函数是神经网络中一个十分重要的概念，它的非线性使得神经网络几乎可以任意逼近任何非线性函数。如果不适用激活函数，无论神经网络有多少层，其每一层的输出都是上一层输入的线性组合，这样构成的神经网络仍然是一个线性模型，表达能力有限。
```

**Comment by fncokg** [comment]
You put two display style equations together with no empty line between them (i.e. eq:权值计算 and eq:激活函数). As a result, the two display style equations will be put in on paragraph in docx and therefore both equations want the paragraph to be labelled as its own identifier. That's the conflict.

Now, I solved this by checking the duplicate target paragraphs before labelling them in commit ceb3a8db6f53a34f3c377371b4511b9a3ae49189. You can now test the new version of filter in your project and close the issue if it works well.

BTW, please check those labels appearing in the `"Reference not found"` warnings. Have they been already defined?

**Comment by JPZ4-5** [comment]
The problem seems to be fixed! Wonderful!

> BTW, please check those labels appearing in the "Reference not found" warnings. Have they been already defined? 

Yes. Parts of WARNINGs are as following. And, Noticing picb/c/d/e are all defined with \subfloat[]{} and no empty line between b&c, d&e. WARNINGs seem not to be fixed after I insert an empty line between them.

As for WARNINGs about sec: ISDJ etc., I attached the part as a txt 
[part_of_WARNINGs.txt](https://github.com/user-attachments/files/18249105/part_of_WARNINGs.txt)
since it's too long.

about picb picc:
```latex
如图\ref{picb}和图\ref{picc}所示分别给出了参数$E_0=\hat{x}$，$a_n=-\hat{z}$，$f_0=250MHz$，$f_w=50MHz$，$t_w=4.2\sigma$时，调制高斯脉冲的时域与频域归一化波形图。

\begin{figure}[h]
\subfloat[]{
    \label{picb}
    \includegraphics[width=7.3cm]{picb.pdf}  
}
\subfloat[]{
    \label{picc}        
    \includegraphics[width=6.41cm]{picc.pdf}
}
\caption{调制高斯脉冲时域与频率波形，时域阻抗元素的存储技术也是时间步进算法并行化的关键技术之一。(a)调制高斯脉冲信号的时域波形；(b)调制高斯脉冲信号的频域波形}
\label{fig1}
\end{figure}
```

about subsec:XXX
```latex
\subsection{单通道卷积}
\label{subsec:单通道卷积}
二维卷积由一维卷积扩展而来，常用于图像处理之中。假定一个二维图像 \(\mathbf{X}\in\mathbb{R}^{M\times N}\) 和二维卷积核 \(\mathbf{W}\in\mathbb{R}^{U\times V}\)，通常 \(U\ll M\)，\(V\ll N\)，两者卷积表达式为 \(\mathbf{Y} = \mathbf{W} \ast \mathbf{X}\) 结果中的元素计算如式\eqref{二维卷积}：
\begin{equation}
    \label{二维卷积}
    y_{i,j} = \sum_{u=1}^U \sum_{v=1}^V \omega_{u,v}x_{i-u+1,j-v+1} 
\end{equation}  

图\ref{fig:二维卷积}给出了二维卷积计算的过程，其中绿色元素表明了卷积结果的第一个元素计算过程，其余元素以此类推，且卷积核在横向和纵向的移动步长均为1个单位。
\begin{figure}[htbp]
    \centering
    \centerline{\includegraphics[width=0.8\linewidth]{pic/二维卷积.png}}        
    \caption{二维卷积}
    \label{fig:二维卷积}
\end{figure}

每个卷积核都会提取输入的某种特征，为了增加特征的丰富程度，常常会使用多个卷积核，即\(\mathbf{W}=\{\mathbf{W}^0,\mathbf{W}^1,\cdots,\mathbf{W}^{C'-1}\},~\mathbf{W}^i\in\mathbb{R}^{U\times V}\)，将输入与每个卷积核得到的多个结果拼接起来。对于以\(\mathbf{X}_{i,j}\)为中心的局部区域，卷积得到的是向量\(\mathbf{Y}_{i,j}=[ \mathbf{Y}^0_{i,j},\mathbf{Y}^1_{i,j},\cdots,\mathbf{Y}^{C'-1}_{i,j}] \)，其中的每一个元素都是与对应的卷积核计算得到的结果。

将结果拼接起来，卷积核可以用一个三维的张量表示，即 \(\mathbf{W}\in\mathbb{R}^{U\times V\times C’}\)，输出结果为\(\mathbf{Y}\in\mathbb{R}^{M'\times N'\times C’}\)。这样由卷积得到的输出为特征图（Feature Maps）。

\subsection{多通道卷积}
节\ref{subsec:单通道卷积}已经介绍了单通道卷积，将其简单扩展就可以得到多通道卷积。假设\(\mathbf{X}\in\mathbb{R}^{M\times N\times C}\)，其中\(C\)表示通道（Channel）数，卷积核的长宽不变。相较于节\ref{subsec:单通道卷积}中的输入，由于输入有多个通道，因此多通道卷积赋予每个通道一个\(U\times V\)的卷积核，这些卷积核构成\(\mathbf{W}^{C'}\in\mathbb{R}^{U\times V\times C}\)，每个通道与对应此通道的卷积核进行卷积后，相加以得到结果。在具体实现中，在完成卷积后，通常会为每个特征图加一个偏置。
```

about eq:CI--1
```latex
由图\ref{fig:切片重构干扰产生原理}可知，切片重构干扰的“切片”过程可以表示为：
\begin{align}
C(t) = x(t) p(t) = x(t) \left[ \text{rect} \left(\frac{t - \tau}{\tau}\right) \ast \sum_{i=0}^{m-1} \delta (t-i T_s) \right]
\label{eq:CI--1}
\end{align}

其中 \(m\) 为采样脉冲数目，由干扰产生原理可知，整段信号被分成了 \(mm\) 段，故采样脉宽 \(\tau = \frac{T}{mn}\) 。重构阶段将采样得到的脉冲信号填充到相邻的时隙之中，该过程可以表示为：
\begin{align}
J_{CI}(t) = \sum_{k=0}^{n-1} p\left(t - \frac{kT}{mn}\right)
\label{eq:CI-0}
\end{align}

为了得到 \(J_{CI}(t)\) 的频谱，先取出第 \(a\) 个子脉冲中第 \(b\) 个片段，进行频谱分析，可以忽略雷达信号的裁频 \(f_c\):
\begin{align}
J_{CI}^{(a,b)}(t) = e^{j\pi K\left(t - \frac{b-1}{mn}T\right)^2}, \quad p = 1, \ldots, m \quad q = 1, \ldots, n \nonumber\\
\frac{a - 1}{m}T + \frac{b-1}{mn}T < t < \frac{a - 1}{m}T + \frac{b}{mn}T
\label{eq:CI-1}
\end{align}

由式\eqref{eq:CI-1}可以得到 \(J_{CI}^{(a,b)}(t)\) 的频谱为：
\begin{align}
J_{CI}^{(a,b)}(f) &= \int_{\frac{a-1}{m}T+\frac{b-1}{mn}T}^{\frac{a-1}{m}T+\frac{b}{mn}T} e^{j\pi K\left(t - \frac{b-1}{mn} T\right)^2} e^{j2\pi ft} dt \nonumber\\
&= A \int_{v_1}^{v_2} e^{\frac{j\pi x^2}{2}} dx
\label{eq:CI-2}
\end{align}

由菲涅尔积分公式可得：
\begin{align}
J_{CI}^{(a,b)}(f) = A \left\{ [c(v_2) + c(v_1)] + j[s(v_2) + s(v_1)] \right\}
\label{eq:CI-3}
\end{align}

其中：
\begin{align}
A &= \frac{\sqrt{T} e^{ -j\pi \left(\frac{f^2}{K} + \frac{2f(b-1)}{mn}T \right)}}{\sqrt{2B}}  \\
v_1 &= \sqrt{2K} \left(\frac{f}{K} - \frac{a-1}{mn} T\right) \\
v_2 &= \sqrt{2K} \left(\frac{a-1}{m} T + \frac{T}{mn} - \frac{f}{K}\right) 
\end{align}

由式\eqref{eq:CI--1}至\eqref{eq:CI-2}可以得到 \(J_{CI}^{(a,b)}(t)\) 的幅度谱为：
\begin{align}
\left| J_{CI}^{(a,b)}(f) \right| = \sqrt{\frac{T}{2B}} \{ \left[ c(v_2) + c(v_1) \right]^2 + \left[ s(v_2) + s(v_1) \right]^\frac{1}{2} \}
\end{align}
```

**Comment by fncokg** [comment]
There are three issues:
1. **Subfigures**: The filter has no subfigures support for now. I'll soon add the support to subfigure numbering. However, I'd notice that `pandoc` itself does not support `\subfloat` in `subfig`, it only supports `subfigure` environment in `subcaption`, AFAIK. 
2. **Section Labelling**: The filter does not support section labels appearing in section bodies rather than inside `\section{}` command, since it searches for the section labels only in `Header` class. I recommend to move all these labels into `\section`, `\subsection` etc.
3. **Special Characters in Labels**: The previous version of the filter does not support special characters such as `-` in labels. This is fixed in commit de76b9a4aa9b02b25897cf2a3cd8bf9888060da6. 

I'll reply to you once the subfigure-support is finished.

**Comment by JPZ4-5** [comment]
Thanks a lot! 2 and 3 are solved. Looking forward to subfigure support!

**Comment by fncokg** [comment]
> Thanks a lot! 2 and 3 are solved. Looking forward to subfigure support!

The support for subfigures is added in the current version (commit 167b2d749d586566941a15327f9832acd515782b). For details of the subfigure, see the [Subfigure Support](https://github.com/fncokg/pandoc-tex-numbering?tab=readme-ov-file#subfigure-support) section in the README.

Again, please test the filter with your own LaTeX source codes and feel free to report any issues you encounter.
